version: '3'
services:
  collector:
    image: grafana/otel-lgtm:0.11.5
    ports:
      - "4317:4317"   # gRPC OTLP
      - "4318:4318"   # http OTLP
      - "3000:3000"   # grafana UI
#    volumes:
#      - ./grafana/dashboards:/otel-lgtm/dashboards
#      - ./grafana/dashboards.yaml:/otel-lgtm/grafana-v11.0.0/conf/provisioning/dashboards/dashboards.yaml