{
 "title": "Java Repo Meta (Cloud)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo",
    "label": "Repo",
    "query": {
     "query": "label_values(repo_prs_open,repo)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Issues Open",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "repo_issues_open{repo=~\"$repo\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "PRs Open",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "repo_prs_open{repo=~\"$repo\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Star Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "repo_stars_count{repo=~\"$repo\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Instrumentations w/ Description",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "instrumentation_libraries_with_description",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Instrumentation w/ Telemetry",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "instrumentation_libraries_with_telemetry",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Description Coverage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "reducer": "mean", "type": "math" }
   ]
  },
  {
   "title": "Telemetry Coverage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$A / $B * 100", "reducer": "mean", "type": "math" }
   ]
  }
 ]
}