
name: Nightly Metrics

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours (at 00:00 and 12:00 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and run Docker container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
          OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
        run: |
          echo "OTEL_EXPORTER_OTLP_ENDPOINT is set: ${OTEL_EXPORTER_OTLP_ENDPOINT:+true}"
          docker build -t github-metrics .
          docker run \
            -e GITHUB_TOKEN="$GITHUB_TOKEN" \
            -e OTEL_EXPORTER_OTLP_ENDPOINT="$OTEL_EXPORTER_OTLP_ENDPOINT" \
            -e OTEL_EXPORTER_OTLP_HEADERS="$OTEL_EXPORTER_OTLP_HEADERS" \
            -e OTEL_EXPORTER_OTLP_PROTOCOL="$OTEL_EXPORTER_OTLP_PROTOCOL" \
            github-metrics
